####################  CALCULO CONTROLES DE CRECIMIENTO Y DESARROLLO


LOGRO05 = DATA[c("A01","IdIntegrante","E02_1","G03","E02","FechaInicio")]

lazy_dt(LOGRO05)

LOGRO05$E02_1_MES = age_calc(as.Date(LOGRO05$E02), enddate = as.Date(LOGRO05$FechaInicio), units = "months", precise = TRUE)

LOGRO05 <- sqldf("SELECT *, 
            CASE WHEN E02_1_MES <= 1 OR E02_1_MES >= 72  THEN 'NO APLICA'
            
                 WHEN (E02_1_MES > 1 AND E02_1_MES < 72) AND G03 IS NULL THEN 'SIN DATO'
                 
                 WHEN (E02_1_MES > 1 AND E02_1_MES < 72) AND G03 = '1'  THEN 'ALCANZADO' ELSE 'POR ALCANZAR' END ESTADO_I
                 FROM LOGRO05")

#CALCULAR HOGARES CON AL MENOS UNA PERSONA POR ALCANZAR
TMP <-data.frame(unique(LOGRO05[LOGRO05$ESTADO_I=="POR ALCANZAR",c(1)]))
colnames(TMP) <- c("A01")

#CALCULAR HOGARES CON AL MENOS UNA PERSONA ALCAZADO
TMP1 <-data.frame(unique(LOGRO05[LOGRO05$ESTADO_I=="ALCANZADO",c(1)]))
colnames(TMP1) <- c("A01")

#CALCULAR HOGARES CON AL MENOS UNA PERSONA SIN DATO
TMPSD <-data.frame(unique(LOGRO05[LOGRO05$ESTADO_I=="SIN DATO",c(1)]))
colnames(TMPSD) <- c("A01")

#CALCULO LOGRO FAMILIAR
LOGRO05 <- sqldf("SELECT LOGRO05.*, 
            CASE 
            WHEN TMPSD.A01 IS NOT NULL THEN 'SIN DATO'
            WHEN TMP.A01 IS NULL AND TMP1.A01 IS NULL THEN 'NO APLICA' 
            WHEN TMP.A01 IS NULL THEN 'ALCANZADO' ELSE 'POR ALCANZAR' END ESTADO_F
            FROM LOGRO05
            LEFT JOIN TMP ON LOGRO05.A01 = TMP.A01
            LEFT JOIN TMP1 ON LOGRO05.A01 = TMP1.A01
            LEFT JOIN TMPSD ON LOGRO05.A01 = TMPSD.A01")

rm(list = ls()[ls() %in% grep("^TMP",ls(),value = TRUE)])
