#################### CALCULO IDENTIFICACION

LOGRO01 <- DATA[c("A01","IdIntegrante","E06_1","E07","E08","E09","E02_1")]

lazy_dt(LOGRO01)

LOGRO01$E08[LOGRO01$E08 =="1"] <- "RC" #ES 1 SISBEN
LOGRO01$E08[LOGRO01$E08 =="2"] <-"TI" #ES 2 SISBEN
LOGRO01$E08[LOGRO01$E08 =="3"] <-"CC" #ES 3 SISBEN
LOGRO01$E08[LOGRO01$E08 =="4"] <-"CE" #ES 4 SISBEN
LOGRO01$E08[LOGRO01$E08 =="5"] <-"DNI" #ES 4 SISBEN
LOGRO01$E08[LOGRO01$E08 =="6"] <-"Pasaporte" #ES 4 SISBEN
LOGRO01$E08[LOGRO01$E08 =="7"] <-"Salvoconducto" #ES 4 SISBEN
LOGRO01$E08[LOGRO01$E08 =="8"] <-"PEP" #ES 4 SISBEN
LOGRO01$E08[LOGRO01$E08 =="99"] <- 0

#CALCULO LOGRO INDIVIDUAL
LOGRO01 <- sqldf("SELECT *,

            CASE    WHEN E02_1 < 7  AND E07 = '2' THEN 'POR ALCANZAR'
                    WHEN E02_1 > 18 AND E07 = '2' THEN 'POR ALCANZAR'
                    WHEN E02_1 BETWEEN 7 AND 18 AND E07 = '2' THEN 'POR ALCANZAR'
            
                 WHEN E06_1 IS NULL OR E07 IS NULL OR E08 IS NULL OR E09 IS NULL OR E02_1 IS NULL THEN 'SIN DATO'
                 
                 WHEN  E06_1 is not null  AND E08 not in ('RC','TI','CC')  AND E09 IS NOT NULL  THEN 'ALCANZADO'
                 
                 WHEN  E06_1 = '999' and E08 = 'RC' AND E02_1 < 7     AND E09 IS NOT NULL THEN 'ALCANZADO' 
                 
                 WHEN  E06_1 = '999' and E08 = 'TI' AND E02_1 BETWEEN 7 AND  17  AND E09 IS NOT NULL  THEN 'ALCANZADO'
                 
                 WHEN  E06_1 = '999' and E08 = 'CC' AND E02_1 >  17  AND E09 IS NOT NULL  THEN 'ALCANZADO'
            
            
            ELSE 'POR ALCANZAR' END ESTADO_I
            FROM LOGRO01")



#CALCULAR HOGARES CON AL MENOS UNA PERSONA POR ALCANZAR
TMP <-data.frame(unique(LOGRO01[LOGRO01$ESTADO_I=="POR ALCANZAR",c(1)]))
colnames(TMP) <- c("A01")
#CALCULO LOGRO FAMILIAR

#CALCULAR HOGARES CON AL MENOS UNA PERSONA SIN DATO
TMPSD <-data.frame(unique(LOGRO01[LOGRO01$ESTADO_I=="SIN DATO",c(1)]))
colnames(TMPSD) <- c("A01")

LOGRO01 <- sqldf("SELECT *, 
            CASE 
            WHEN TMPSD.A01 IS NOT NULL THEN 'SIN DATO'
            WHEN TMP.A01 IS NULL THEN 'ALCANZADO' ELSE 'POR ALCANZAR' END ESTADO_F
            FROM LOGRO01
            LEFT JOIN TMP USING(A01)
            LEFT JOIN TMPSD USING(A01)")

rm(list = ls()[ls() %in% grep("^TMP",ls(),value = TRUE)])
